kind: pipeline
type: docker
name: default

steps:
  - name: dependencies
    image: node
    commands:
      - curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7
      - pnpm i

  - name: lint
    image: node
    commands:
      - npm run lint:ci
    depends: [dependencies]

  - name: test
    image: node
    commands:
      - npm run test
    depends: [lint]
