kind: pipeline
type: docker
name: default

steps:
  - name: dependencies
    image: node
    commands:
      - yarn

  - name: lint
    image: node
    commands:
      - yarn lint:ci
    depends: [dependencies]

  - name: test
    image: node
    commands:
      - yarn test
    depends: [lint]
